services:
  backend:
    build: ./analyzer_api
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch

  frontend:
    build: ./frontend_analyzer/iis_analys
    ports:
      - "5173:5173"
    depends_on:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata: